aggregate/urls.py
from django.urls import path
from . import views 


app_name = "aggregate"
urlpatterns = [
    path('chart-data', views.chart_view, name='chart_data'),
    path('export_aggregate_xls', views.exportFamilyandPopulation, name='export_aggregate'),
    path('get-chart-data/', views.get_chart_data, name='get_chart_data'),
   # path('infant_counts_report/', views.infant_counts_report, name='infant_counts_report'),
    #path('population_data', views.get_data, name='population_data'),
]
    #path('print_aggregate', views.print_aggregate, name="print_aggregate"),
    # path('<int:id>/generatePDF/', views.generatePDF, name='generatePDF'),
    #path('export_pdf', views.export_pdf, name='export_pdf'),
     #path('aggregated_data', views.aggregated_data, name='aggregated_data'),

base/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.getRoutes, name="routes"),
    path('persons/',views.getPersons, name="persons"),
    path('persons/<str:pk>/',views.getPerson, name="person"),
    path('households/',views.getHousehold, name="householapi"),
    path('aggregate/',views.getAggregaredHousehold, name="aggregate"),
    path('polygons/',views.getFlood, name="flood"),
    path('municipal/',views.getMunicipal, name="municipal"),
    path('barangay/',views.getBarangay, name="barangay"),
    path('households/<str:pk>/brgy/',views.getBrgy, name="households-barangay"),
    path('households/<str:pk>/info/',views.getHouseholdInfo, name="households-info"),
    path('households/permun/',views.getHouseholdPerMun, name="households-per-mun"),
    path('family/permun/',views.getFamilyPerMun, name="family-per-mun"),
    path('brgy/<str:pk>/info/',views.getBrgyInfo, name="brgy-info"),
    path('reports/',views.getTotalReport, name="total-report"),
    path('reports/flood/<str:pk>/',views.getFloodReportPerBarangay, name="flood-report"),
    path('flood/<str:pk>/info/',views.getFloodHazardInfo, name="flood-info"),
    path('flood/',views.getOverAllFloodReport, name="flood-over-all"),
    path('point/<str:pk>/senior/',views.getpointsenior, name="point-senior"),
]

household_geodatabase/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView

## Set this if using django rest framework
# from django.urls import path, include
# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView,
# )
# from rest_framework.routers import DefaultRouter
# from users.views import UserViewSet

admin.site.index_title = "Household Database"
admin.site.site_title = "Household Database Admin Portal"
admin.site.site_header = "Household Database Information System"

urlpatterns = [
    # Redirect home view to admin:index
    path('', RedirectView.as_view(url=reverse_lazy('admin:index'))),
    path("admin/", admin.site.urls),
    path('',include('household.urls')),
    path('address/',include('library.urls')),
    ## URL for api rest framework
    #path('api-auth/', include('rest_framework.urls')),
    #path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    #path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

#router = DefaultRouter()
#router.register('user',UserViewSet,basename='user')

#urlpatterns += router.urls

aggregate/models.py
from email.policy import default
from tabnanny import verbose
from django.db import models
from library.models import Municipalities, Barangays

    
class AggregatedFamiliesandPopulation(models.Model):
  munname = models.CharField(primary_key=True,max_length=50,verbose_name='Municipality')
  brgyname = models.CharField(max_length=50,null=True,verbose_name='Barangay')
  purok_name = models.CharField(max_length=50,null=True,verbose_name='Purok')
  households = models.IntegerField(default=0,verbose_name='No. of Households')
  families = models.IntegerField(default=0,verbose_name='No. of Families')
  male = models.IntegerField(default=0,verbose_name='Individuals (M)')
  female = models.IntegerField(verbose_name='Individuals (F)')
  male_infant = models.IntegerField(verbose_name='Infant 0-11months (M)')
  female_infant = models.IntegerField(verbose_name='Infant 0-11months (F)')
  male_children = models.IntegerField(verbose_name='Children 1-17y/o (M)')
  female_children = models.IntegerField(verbose_name='Children 1-17y/o (F)')
  male_adult = models.IntegerField(verbose_name='Adult 18-59y/o (M)')
  female_adult = models.IntegerField(verbose_name='Adult 18-59y/o (F)')
  male_elderly = models.IntegerField(verbose_name='Elderly 60y/o above (M)')
  female_elderly = models.IntegerField(verbose_name='Elderly 60y/o above (F)')
  pwd_male = models.IntegerField(verbose_name='PWD (M)')
  pwd_female = models.IntegerField(verbose_name='PWD (F)')
  ip_male = models.IntegerField(verbose_name='IP (M)')
  ip_female = models.IntegerField(verbose_name='IP (F)')

  class Meta:
    db_table = 'aggregate'
    verbose_name_plural = "No. of families and population"

# Create your models here.

# class Sampletable(models.Model):
#   stpsgccode = models.CharField(max_length=255,primary_key=True)
#   stmunname = models.CharField(max_length=255,unique=True)
#   stcreated_at = models.DateField(auto_now_add=True)
#   stupdated_at = models.DateField(auto_now=True)

#   def __str__(self):
#         return self.munname

#   class Meta:
#     verbose_name_plural = "Sampletable"

aggregate/views.py
from aggregate.models import AggregatedFamiliesandPopulation
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl import Workbook
from django.db.models import Sum


def index(request): 
    return render(request,'aggregate/index.html')


def exportFamilyandPopulation(request):
    try:
        user = request.user
        # Check if user belongs to the "municipality" group or is an admin
        if user.groups.filter(name='municipality').exists() or user.is_superuser:
            if user.is_superuser:
                aggregated = AggregatedFamiliesandPopulation.objects.all()
            else:
                user_location = user.userlocation
                municipality = user_location.psgccode_mun
                aggregated = AggregatedFamiliesandPopulation.objects.filter(munname=municipality)

            workbook = Workbook()
            worksheet = workbook.active

            worksheet.print_options.fit_to_page = True
            worksheet.print_options.fit_to_width = 1

            bold_font = Font(bold=True)
            fill = PatternFill(start_color='FFCC00', end_color='FFCC00', fill_type='solid')
            headers = [
                'Municipality', 'Barangay', 'No. of Households', 'No. of Families', 'Individuals (M)', 'Individuals (F)',
                'Infant 0-11months (M)', 'Infant 0-11months (F)', 'Children 1-17y/o (M)', 'Children 1-17y/o (F)',
                'Adult 18-59y/o (M)', 'Adult 18-59y/o (F)', 'Elderly 60y/o above (M)', 'Elderly 60y/o above (F)',
                'PWD (M)', 'PWD (F)','IP (M)', 'IP (F)'
            ]

            for col_num, header_title in enumerate(headers, 1):
                cell = worksheet.cell(row=1, column=col_num, value=header_title)
                cell.font = bold_font
                cell.fill = fill
                column_letter = get_column_letter(col_num)
                worksheet.column_dimensions[column_letter].width = 18

            for data in aggregated:
                worksheet.append([
                    data.munname, data.brgyname, data.households, data.families, data.male, data.female, data.male_infant,
                    data.female_infant, data.male_children, data.female_children, data.male_adult,
                    data.female_adult, data.male_elderly, data.female_elderly, data.pwd_male, data.pwd_female, data.ip_male, data.ip_female
                ])

            response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
            response['Content-Disposition'] = 'attachment; filename=FamiliesandPopulation.xlsx'
            workbook.save(response)
            return response

        else:
            return HttpResponse('You do not have permission to export data')

    except Exception as e:
        error_message = f'An error occurred: {str(e)}'
        return render(request, 'aggregate/error_template.html', {'error_message': error_message})


def chart_view(request):
    return render(request, 'aggregate/population_chart.html')

def generate_chart_data():
    age_groups = [
        ('Infant 0-11months', 'male_infant', 'female_infant'),
        ('Children 1-17y/o', 'male_children', 'female_children'),
        ('Adult 18-59y/o', 'male_adult', 'female_adult'),
        ('Elderly 60y/o above', 'male_elderly', 'female_elderly'),
    ]

    age_group_population = []
    for age_group, male_field, female_field in age_groups:
        total_population = AggregatedFamiliesandPopulation.objects.aggregate(
            total_male=Sum(male_field),
            total_female=Sum(female_field)
        )
        total_population = total_population['total_male'] + total_population['total_female']

        age_group_population.append({
            'Age Group': age_group,
            'Total Population': total_population
        })

    infant_counts = AggregatedFamiliesandPopulation.objects.values('munname').annotate(
        total_infants=Sum('male_infant') + Sum('female_infant')
    )

    chart_data = {
        'age_group_population': age_group_population,
        'infant_counts': []
    }
    for result in infant_counts:
        municipality_name = result['munname']
        total_infants = result['total_infants']
        chart_data['infant_counts'].append({'Municipality': municipality_name, 'Total Infants': total_infants})

    return chart_data

def get_chart_data(request):
    chart_data = generate_chart_data()
    return JsonResponse(chart_data, safe=False)


def infant_counts_report(request):
    return render(request, 'chart.html')

templates/aggregate/change_list.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_list %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}"/>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.3.2"></script>
    
    {% if cl.formset %}
        <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}"/>
    {% endif %}
    {% if cl.formset or action_form %}
        <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    {% endif %}
    {{ media.css }}
    {% if not actions_on_top and not actions_on_bottom %}
        <style>
            #changelist table thead th:first-child {
                width: inherit
            }
            
        </style>
    {% endif %}
    
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    {{ media.js }}
{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-list{% endblock %}

{% if not is_popup %}
    {% block breadcrumbs %}
    <div class="row mb-2">
        <div class="col-sm-6">
            <h2>Families and Population</h2>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{% url 'admin:index' %}"><i class="fas fa-tachometer-alt"></i> {% trans 'Home' %}</a></li>
                <li class="breadcrumb-item"><a href="{% url 'admin:app_list' app_label=cl.opts.app_label %}">{{ cl.opts.app_config.verbose_name }}</a></li>
                <li class="breadcrumb-item active">{{ cl.opts.verbose_name_plural|capfirst }}</li>  
            </ol>
        </div>

    </div>    
    {% endblock %}
{% endif %}

{% block coltype %}flex{% endblock %}



{% block content %}
  
    <div id="content-main" class="container-fluid">
        {% if cl.formset.errors %}
            <p class="errornote">
                {% if cl.formset.total_error_count == 1 %}{% trans "Please correct the error below." %}{% else %}
                    {% trans "Please correct the errors below." %}{% endif %}
            </p>
            {{ cl.formset.non_form_errors }}
        {% endif %}
        <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
           
            <div class="d-flex justify-content-end row p-3">
                {% block search %}{% search_form cl %}{% endblock %}
                <!--  -->
                {% block object-tools %}
        
                <div class="col-md-{% if cl.has_filters %}4{% else %}4{% endif %}">
                    <div class="d-flex justify-content-end">

                        
                    </div>
                        {% if cl.has_filters %}
                        <span class="float-sm-right">
                            <a href="{% url 'aggregate:export_aggregate'%}" 
                            class="btn btn-primary btn-sm text-sm">
                                <i class="fa fa-download"></i> Download
                            </a>
                            <a href="#"
                            class="btn btn-dark btn-sm text-light ml-1" data-toggle="collapse" data-target="#changelist-filter" aria-expanded="false" aria-controls="changelist-filter">
                                <i class="fas fa-filter"></i>
                                {% trans 'Filter' %}
                            </a>
                        </span>
                            {% endif %}
                        {% block object-tools-items %}
                            {% if has_add_permission %}
                                <span class="float-sm-right">
                                    {% url cl.opts|admin_urlname:'add' as add_url %}
                                    <a href="{% add_preserved_filters add_url is_popup to_field %}"
                                    class="btn btn-primary btn-sm text-light">
                                        <i class="fas fa-plus"></i>
                                        {% blocktrans with cl.opts.verbose_name as name %}Add {{ name }}{% endblocktrans %}
                                    </a>
                                </span>
                            {% endif %}
                        {% endblock %}
                </div>
                {% endblock %}
                
            </div>
            <!--  -->
            {% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}

            {% block filters %}
                {% if cl.has_filters %}
                    <div id="changelist-filter" class="collapse" >
                        <h2>{% trans 'Filter' %}</h2>
                        {% for spec in cl.filter_specs %}{% admin_list_filter cl spec %}{% endfor %}
                    </div>
                {% endif %}
            {% endblock %}

            <form id="changelist-form" method="post"{% if cl.formset.is_multipart %}
                  enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}

                
                {% if cl.formset %}
                    <div>{{ cl.formset.management_form }}</div>
                {% endif %}

                {% block result_list %}
                    {% if action_form and actions_on_top and cl.show_admin_actions %}{% admin_actions %}{% endif %}
                    {% result_list cl %}
                    {% if action_form and actions_on_bottom and cl.show_admin_actions %}{% admin_actions %}{% endif %}
                {% endblock %}
                 {% block pagination %}{% pagination cl %}{% endblock %}
            </form>
        </div>
    </div>
    {% include 'aggregate/chart.html' %}
{% endblock %}


{% block extra_js %}
<script src="{% static 'admin-lte/plugins/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
<script>

$(function () {
  $('#result_list').DataTable(
   {
        "paging": false,
      //  "lengthChange": true,
        //"searching": true,
        //"ordering": true,
       // "info": true,
       // "autoWidth": true,
     });
  });
  

</script>

<script>
    $(document).ready(function(){
        $.each($('#result_list_wrapper').children().filter(':last-child').children(), function( k, v ) {
            v.remove();
        });
        $('.card').append($('<div class="card-footer"></div>'));
        $('.card-footer').append($('.paginator'));
        $('.card-footer').addClass('text-center')
        $('.paginator').addClass('col-md-12');

        // moving actions div to the header of datatable
        try{
            $('.dataTables_wrapper :first-child :first-child')[0].remove();
            $actions = $('.actions');
            $actions.addClass('col-sm-6 col-md-6');
            $actions.prependTo($('.dataTables_wrapper :first-child')[0]);
        }catch(err){
            // so no data yet 
        }

});

</script>
{% endblock %}

templates/aggregate/chart.html
<div style="width: 70%; height: 100%; display: flex; flex-direction: column; justify-content: center; align-items: center; margin-left: 250px; margin-top:100px;">
    <!-- First Chart: Population by Age Group -->
    <canvas id="chart" style="border: 1px solid #262626;"></canvas>
    <p id="caption1" style="margin-top: 10px; text-align: center;"></p>
    <div id="description1" style="margin-top: 10px; text-align: center;">
        <p>This detailed bar chart visually presents the changing population in Agusan del Norte across different age groups.</p>
        <p>Each bar corresponds to an age group and its height corresponds to the total population of that group. </p>
        <p>This visual representation helps you understand the distribution of the population and provides insights into the variety of ages in the region.</p>
    </div>

    <!-- Second Chart: Infant Counts by Municipality -->
    <canvas id="chart2" style="border: 1px solid #262626;"></canvas>
    <p id="caption2" style="margin-top: 10px; text-align: center;"></p>
    <div id="description2" style="margin-top: 10px; text-align: center;">
        <p>This bar chart displays the total number of infants per municipality.</p>
        <p>Each bar represents a municipality, and the height of the bar corresponds to the total number of infants.</p>
        <p>Use this chart to visualize the distribution of infants across different municipalities.</p>
    </div>
</div>
<script>
    fetch("{% url 'aggregate:get_chart_data' %}")
        .then(response => response.json())
        .then(data => {
            // First Chart: Population by Age Group
            const labels1 = data.age_group_population.map(item => item['Age Group']);
            const values1 = data.age_group_population.map(item => item['Total Population']);

            const ctx1 = document.getElementById('chart').getContext('2d');
            const myChart1 = new Chart(ctx1, {
                type: 'bar',
                data: {
                    labels: labels1,
                    datasets: [{
                        label: 'Total Population',
                        data: values1,
                        backgroundColor: 'rgba(67, 118, 108, 0.8)',
                    }]
                },
                options: {
                    responsive: true,
                    plugins: {
                        title: {
                            display: true,
                            text: 'Population by Age Group',
                            fontSize: 16
                        }
                    }
                }
            });

            // Calculate and set the total population count
            const totalPopulation1 = values1.reduce((sum, value) => sum + value, 0);
            document.getElementById('caption1').textContent = `Total Population: ${totalPopulation1}`;

            // Second Chart: Infant Counts by Municipality
            const labels2 = data.infant_counts.map(item => item['Municipality']);
            const values2 = data.infant_counts.map(item => item['Total Infants']);

            const ctx2 = document.getElementById('chart2').getContext('2d');
            const myChart2 = new Chart(ctx2, {
                type: 'bar',
                data: {
                    labels: labels2,
                    datasets: [{
                        label: 'Total Infants',
                        data: values2,
                        backgroundColor: 'rgba(255, 99, 132, 0.7)'
                    }]
                },
                options: {
                    responsive: true,
                    plugins: {
                        title: {
                            display: true,
                            text: 'Infant Counts by Municipality',
                            fontSize: 16
                        }
                    }
                }
            });

            // Calculate and set the total number of infants
            const totalInfants2 = values2.reduce((sum, value) => sum + value, 0);
            document.getElementById('caption2').textContent = `Total Infants: ${totalInfants2}`;
        })
        .catch(error => console.error("Error fetching chart data:", error));
</script>

templates/aggregate/error_template.html
<!DOCTYPE html>
<html>
<head>
    <title>Error</title>
</head>
<body>
    <h1>Error</h1>
    <p>{{ error_message }}</p>
</body>
</html>

templates/aggregate/index.html
{% extends "adminlte/base.html" %}
{% load i18n static %}
{% load admin_menu %}
{% load leaflet_tags %}

{% block coltype %}colMS{% endblock %}
{% block bodyclass %}{{ block.super }} dashboard{% endblock %}



{% block content %}


{% endblock %}